{% set name = "panda3d" %}
{% set version = "1.10.13" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: b865882d8cbb44e7a9b1e030ecc071e689391644eb68b0d8ed78b970e8d4d2c7
    patches:
      - patches/osx_python_dep.patch  # [osx]
  # Additional tools
  - url: https://www.panda3d.org/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}-tools-mac.tar.gz  # [osx]
    sha256: a626a087d2134ae98b876d663a0c9695f7ee197e13c0c3be6eb978dd99699825  # [osx]

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}
  missing_dso_whitelist:                  # [osx]
    - Frameworks/Cg.framework/Cg          # [osx]

requirements:
  build:
    - {{ compiler('c') }}                 # [not win]
    - {{ compiler('cxx') }}               # [not win]
    - make                                # [not win]
    - rsync                               # [not win]
    - vs2017_win-64                       # [win64]
    - vs2017_win-32                       # [win32]
    - cmake
    - pkg-config
    - doxygen
    - {{ cdt('mesa-dri-drivers') }}       # [linux]
    - {{ cdt('mesa-libgl-devel') }}       # [linux]
    - {{ cdt('mesa-libegl-devel') }}      # [linux]
    - {{ cdt('libselinux-devel') }}       # [linux]
 host:
    - python
    - numpy
    # Package to specify to panda3d
    - eigen
    - assimp
    - bullet
    - ffmpeg
    - freetype
    - libjpeg-turbo
    - libpng
    - libvorbis
    - openal-soft
    - openssl
    - openexr
    - tifffile
    - zlib
    # Other packages
    - pip
    - libogg
    - pillow
    # Linux GL packages
    - xcb-util                           # [linux]
    - xcb-util-wm                        # [linux]
    - xcb-util-keysyms                   # [linux]
    - xcb-util-image                     # [linux]
    - xcb-util-renderutil                # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libsm                         # [linux]
    - xorg-libice                        # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-xf86vidmodeproto              # [linux]
  run:
    - python
    # Run dep
    - bullet
    - ffmpeg
    - openal-soft
    - openssl
    - tifffile
    # Explicit dso
    - libtiff
    - ilmbase
    - libffi
    - ncurses          # [not win]
    - readline         # [not win]
    - sqlite
    - tk
    - xz
    # numpy
    - {{ pin_compatible('numpy') }}
    # Linux GL packages
    - libxcb                             # [linux]
    - xcb-util-wm                        # [linux]
    - xcb-util-keysyms                   # [linux]
    - xcb-util-image                     # [linux]
    - xcb-util-renderutil                # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libsm                         # [linux]
    - xorg-libice                        # [linux]
    - xorg-xf86vidmodeproto              # [linux]

test:
  imports:
    - panda3d

about:
  home: https://www.panda3d.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Panda3D is a game engine, a framework for 3D rendering and game development for Python and C++ programs
  description: |
    Panda3D is a game engine, a framework for 3D rendering 
    and game development for Python and C++ programs. Panda3D 
    is open-source and free for any purpose, including commercial 
    ventures, thanks to its liberal license. To learn more about 
    Panda3D's capabilities, visit the gallery and the feature list. 
    To learn how to use Panda3D, check the documentation resources. 
    If you get stuck, ask for help from our active community.
  doc_url: https://docs.panda3d.org/1.10/python/index
  dev_url: https://github.com/panda3d/panda3d

extra:
  recipe-maintainers:
    - ymontmarin
