{% set version = "1.10.14" %}

package:
  name: panda3d
  version: {{ version }}

source:
  - url: https://github.com/panda3d/panda3d/archive/v{{ version }}.tar.gz
    sha256: 3ff568db545102f87d3e1191ba6a2f3cdc97ff2f62056973cf354743dd880591
    patches:
      - patches/osx_python_dep.patch  # [osx]
  # Additional tools
  - url: https://www.panda3d.org/download/panda3d-{{ version }}/panda3d-{{ version }}-tools-mac.tar.gz  # [osx]
    sha256: e172d1941a7be1d072de466bc0ea29a8d0d71e16a9aed45b86f69f177ad2813a  # [osx]

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('panda3d', max_pin='x.x') }}
  missing_dso_whitelist:                  # [osx]
    - Frameworks/Cg.framework/Cg          # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                                # [not win]
    - rsync                               # [not win]
    - cmake
    - pkg-config
    - doxygen
    - {{ cdt('mesa-dri-drivers') }}       # [linux]
    - {{ cdt('mesa-libgl-devel') }}       # [linux]
    - {{ cdt('mesa-libegl-devel') }}      # [linux]
    - {{ cdt('libselinux-devel') }}       # [linux]
  host:
    - python
    - numpy
    # Package to specify to panda3d
    - eigen
    - assimp
    - bullet-cpp
    - ffmpeg
    - freetype
    - libjpeg-turbo
    - libpng
    - libvorbis
    - openal-soft
    - openssl
    - openexr  2.5.5
    - tifffile
    - zlib
    - harfbuzz
    - opusfile
    - libvorbis
    # Other packages
    - bison
    - pip
    - libogg
    - pillow
    # Linux GL packages
    - xcb-util                           # [linux]
    - xcb-util-wm                        # [linux]
    - xcb-util-keysyms                   # [linux]
    - xcb-util-image                     # [linux]
    - xcb-util-renderutil                # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libsm                         # [linux]
    - xorg-libice                        # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-xf86vidmodeproto              # [linux]
  run:
    - python
    # Run dep
    - ffmpeg
    - openal-soft
    - openssl
    - tifffile
    # Explicit dso
    - libtiff
    - ilmbase
    - libffi
    - ncurses          # [not win]
    - readline         # [not win]
    - sqlite
    - tk
    - xz
    # numpy
    - {{ pin_compatible('numpy') }}
    # Linux GL packages
    - libxcb                             # [linux]
    - xcb-util-wm                        # [linux]
    - xcb-util-keysyms                   # [linux]
    - xcb-util-image                     # [linux]
    - xcb-util-renderutil                # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libsm                         # [linux]
    - xorg-libice                        # [linux]
    - xorg-xf86vidmodeproto              # [linux]

test:
  imports:
    - panda3d

about:
  home: https://www.panda3d.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Panda3D is a game engine, a framework for 3D rendering and game development for Python and C++ programs
  description: |
    Panda3D is a game engine, a framework for 3D rendering 
    and game development for Python and C++ programs. Panda3D 
    is open-source and free for any purpose, including commercial 
    ventures, thanks to its liberal license. To learn more about 
    Panda3D's capabilities, visit the gallery and the feature list. 
    To learn how to use Panda3D, check the documentation resources. 
    If you get stuck, ask for help from our active community.
  doc_url: https://docs.panda3d.org/1.10/python/index
  dev_url: https://github.com/panda3d/panda3d

extra:
  recipe-maintainers:
    - ymontmarin
