conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
test: native_and_emulated
azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: "C:\\bld"
      MINIFORGE_HOME: "C:\\Miniforge"
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: True
